Performance: Generate part combinations dynamically, rather than storing them all
TryphonX/CMS-Tuning-Calculator pull request #1
Opened 2024-10-29 01:19 UTC by joshbarrass

The current implementation uses the [combinations](https://www.npmjs.com/package/combinations) library to generate all possible combinations of parts at once, storing them in a 2D array. This works well enough for the engines currently implemented, as they do not have enough tunable parts for this to cause any problems. However, some of the DLC engines, such as the _V8 M177 Twin-Turbo AWD (DBX)_ from the Aston Martin DLC, have considerably more tunable parts. The M177, for example, has 24 tunable parts, compared with e.g. the _V8 OHV SS_, which has 18 -- a 2^6 = 64× increase in the number of part combinations. For this engine, the current implementation will quickly consume several gigabytes of memory and freeze until the browser kills it, meaning it never finds a good combination for this engine.

This PR replaces the current implementation with a dynamic version with a ~constant memory footprint. Rather than generating and storing a list of all combinations, only one combination is generated at a time and only the best combination is ever stored. This is achieved with a bitmask method; we iterate from 1 (0 is pointless) to 2^N, where N is the number of parts, and each bit in this value corresponds to whether or not a part is included in the combination. 

This method drastically reduces the memory footprint of the auto-generator, allowing it to be used without crashing for engines with more parts, such as the _V8 M177 Twin-Turbo AWD (DBX)_. It also has a small, but noticeable, improvement on the performance for the existing engines. The use of this method also eliminates the need for the combinations library, and so this has also been removed in this PR.

2024-10-29 23:56 UTC, TryphonX requested changes
Great addition to the project. Only objection is `Common.ts @ ln 224`, minor issue with eslint due to the array being declared with `let` instead of `const` when it is not reassigned.

I could fix it myself, but I wouldn't want to overwrite your solution.

2024-10-30 08:06 UTC, joshbarrass commented
Oops, my bad. I'll fix that now.

2024-10-30 08:08 UTC, joshbarrass commented
Should now be fixed.

2024-10-30 22:58 UTC, TryphonX approved these changes

2024-10-30 22:58 UTC, merged